# Generated by Django 5.0.4 on 2024-04-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Назва Вина')),
                ('count', models.IntegerField(verbose_name='Кількість на складі')),
                ('image', models.ImageField(upload_to='', verbose_name='Картинка')),
                ('sugar', models.CharField(max_length=30, verbose_name='Солодкість')),
                ('country', models.CharField(max_length=30, verbose_name='Країна походження')),
                ('description', models.TextField(verbose_name='Опис')),
                ('fullDescription', models.TextField(verbose_name='Повний опис')),
                ('volume', models.IntegerField(verbose_name="Об'єм")),
                ('strength', models.IntegerField(verbose_name='Крепкость')),
                ('exposureTime', models.CharField(max_length=30, verbose_name='Час витримки')),
            ],
            options={
                'verbose_name': 'Вино',
                'verbose_name_plural': 'Вина',
            },
        ),
    ]
