# Generated by Django 5.0.4 on 2024-04-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wine', '0003_alter_wine_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='color',
            field=models.CharField(default='Біле', max_length=30, verbose_name='Колір'),
            preserve_default=False,
        ),
    ]
